version: "2"
services:
  back:
    build: .
    ports:
      - 4001:4001
    volumes:
      - ./src/:/app/src
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./data/mywiki/markdown:/data/wiki/
    command: npm run start
    env_file:
      - ./env/dev.env
